#include <cuda_runtime.h>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
constexpr int S=25,Q=S*S*S*S,STRIDE=570;constexpr uint64_t MULT=6364136223846793005ULL;
#define CK(x) do{cudaError_t e=(x);if(e!=cudaSuccess){std::fprintf(stderr,"%s\n",cudaGetErrorString(e));std::exit(2);}}while(0)
struct R{uint64_t s,i;__device__ uint32_t n(){uint64_t o=s;s=o*MULT+i;uint32_t x=uint32_t(((o>>18)^o)>>27),r=uint32_t(o>>59);return(x>>r)|(x<<((-r)&31));}__device__ void init(uint64_t v){s=0;i=(0x484AULL<<1)|1;n();s+=v;n();}__device__ int b(int v){return int(n()%uint32_t(v));}__device__ double u(){return double(n())/4294967296.0;}};
__device__ uint64_t ds(uint64_t v,uint64_t a,uint64_t b){v=(v^a)*0x9E3779B97F4A7C15ULL;v^=v>>29;v=(v^b)*0x9E3779B97F4A7C15ULL;v^=v>>29;return v;}
__device__ int k(unsigned char a,unsigned char b,unsigned char c,unsigned char d){return((int(a)*S+b)*S+c)*S+d;}
__global__ void run(const unsigned char*t,const uint16_t*l,int count,const double*q,uint64_t seed,int it,double t0,double t1,double*out,unsigned char*ob){int z=blockIdx.x*blockDim.x+threadIdx.x;if(z>=count)return;const unsigned char*x=t+size_t(z)*STRIDE;int n=l[z];R r;r.init(ds(seed,z,0));unsigned char b[S],bestb[S];for(int i=0;i<S;++i)b[i]=i;for(int i=S-1;i>0;--i){int j=r.b(i+1);unsigned char v=b[i];b[i]=b[j];b[j]=v;}double cur=0;for(int p=3;p<n;++p)cur+=q[k(b[x[p-3]],b[x[p-2]],b[x[p-1]],b[x[p]])];double best=cur;for(int i=0;i<S;++i)bestb[i]=b[i];double cool=it?pow(t1/t0,1.0/double(it)):1,temp=t0;for(int step=0;step<it;++step){int a=r.b(S),c=r.b(S);if(a!=c){double d=0;for(int p=3;p<n;++p){unsigned char s0=x[p-3],s1=x[p-2],s2=x[p-1],s3=x[p];if(s0==a||s0==c||s1==a||s1==c||s2==a||s2==c||s3==a||s3==c){unsigned char a0=b[s0],a1=b[s1],a2=b[s2],a3=b[s3];unsigned char c0=s0==a?b[c]:(s0==c?b[a]:a0),c1=s1==a?b[c]:(s1==c?b[a]:a1),c2=s2==a?b[c]:(s2==c?b[a]:a2),c3=s3==a?b[c]:(s3==c?b[a]:a3);d+=q[k(c0,c1,c2,c3)]-q[k(a0,a1,a2,a3)];}}if(d>=0||r.u()<exp(d/temp)){unsigned char v=b[a];b[a]=b[c];b[c]=v;cur+=d;if(cur>best){best=cur;for(int i=0;i<S;++i)bestb[i]=b[i];}}}temp*=cool;}out[z]=best/double(n-3);for(int i=0;i<S;++i)ob[size_t(z)*S+i]=bestb[i];}
template<class T>bool rd(T*p,size_t n){return std::fread(p,sizeof(T),n,stdin)==n;}
int main(){char m[8];if(!rd(m,size_t(8))||std::memcmp(m,"P484QF1\0",8))return 3;uint32_t h[2];uint64_t seed;double temp[2];if(!rd(h,size_t(2))||!rd(&seed,size_t(1))||!rd(temp,size_t(2)))return 3;size_t count=h[0];int it=h[1];if(!count||count>(1u<<20)||temp[0]<=0||temp[1]<=0)return 4;std::vector<uint16_t>len(count);std::vector<unsigned char>tok(count*STRIDE),boards(count*S);std::vector<double>quad(Q),scores(count);if(!rd(len.data(),count)||!rd(tok.data(),count*STRIDE)||!rd(quad.data(),Q))return 3;for(auto n:len)if(n<4||n>STRIDE)return 4;uint16_t*dl;unsigned char*dt,*db;double*dq,*doo;CK(cudaMalloc(&dl,count*sizeof(uint16_t)));CK(cudaMalloc(&dt,count*STRIDE));CK(cudaMalloc(&db,count*S));CK(cudaMalloc(&dq,Q*sizeof(double)));CK(cudaMalloc(&doo,count*sizeof(double)));CK(cudaMemcpy(dl,len.data(),count*sizeof(uint16_t),cudaMemcpyHostToDevice));CK(cudaMemcpy(dt,tok.data(),count*STRIDE,cudaMemcpyHostToDevice));CK(cudaMemcpy(dq,quad.data(),Q*sizeof(double),cudaMemcpyHostToDevice));run<<<(count+127)/128,128>>>(dt,dl,int(count),dq,seed,it,temp[0],temp[1],doo,db);CK(cudaGetLastError());CK(cudaDeviceSynchronize());CK(cudaMemcpy(scores.data(),doo,count*sizeof(double),cudaMemcpyDeviceToHost));CK(cudaMemcpy(boards.data(),db,count*S,cudaMemcpyDeviceToHost));if(std::fwrite(scores.data(),sizeof(double),count,stdout)!=count||std::fwrite(boards.data(),1,count*S,stdout)!=count*S)return 5;return 0;}
