#!/usr/bin/env python3
"""Bounded scale-history inversion for Phase 356's canonical 7x7 module tile.

Tests whether the exact two-level (250/255) 7x7 grayscale primitive can be
generated by resizing any smaller 1..6 x 1..6 raster through Pillow's six
standard resamplers. For each size/filter, a linear resize operator is built
from basis images and an unconstrained least-squares source is solved. This is
a generous lower bound: if arbitrary continuous source intensities cannot
reproduce the target, a binary or ordinary 8-bit source cannot. The fitted
source is also clipped/rounded to 8-bit and rendered through the real Pillow
path for exact byte comparison.

Matched controls are random 7x7 two-level masks with the exact same 250/255
counts, each receiving the full model search. They calibrate whether a low
best-fit error is special to the observed tile rather than generic when a 6x6
source is allowed to approximate a 7x7 target.
"""

import argparse
import hashlib
import json
from pathlib import Path

import numpy as np
from PIL import Image

from qr_fafafa_module_lock_audit import EYE_BOXES, load_eyes, module_patch, white_ring_modules

REPO_ROOT=Path(__file__).resolve().parents[2]
IMAGE_PATH=REPO_ROOT/"doc"/"img"/"gsmg_puzzle_stage1.png"
EXPECTED_SHA256="38125bbdf1ea58b9b30b075bc6bf71e4089d04bba37098317e47097e2f2a1830"
FILTERS={"nearest":Image.Resampling.NEAREST,"box":Image.Resampling.BOX,
         "bilinear":Image.Resampling.BILINEAR,"hamming":Image.Resampling.HAMMING,
         "bicubic":Image.Resampling.BICUBIC,"lanczos":Image.Resampling.LANCZOS}
NULL_TRIALS=500; NULL_SEED=20260821
EXPECTED_CANONICAL_MODULES=[(1,5),(2,5),(3,5),(4,5)]
EXPECTED_BEST=("hamming",6,6,0.7538455045589266,22)

def sha256_of(p):return hashlib.sha256(p.read_bytes()).hexdigest()

def module_gray_patches():
    eye=load_eyes()[0][:,:,0]
    return {m:module_patch(eye,m).copy() for m in white_ring_modules()}

def canonical_patch():
    patches=module_gray_patches(); groups={}
    for m,p in patches.items(): groups.setdefault(p.tobytes(),[]).append(m)
    eligible=[ms for ms in groups.values() if set(np.unique(patches[ms[0]])) <= {250,255}]
    best=max(eligible,key=lambda ms:(len(ms),ms))
    return patches[best[0]],best,sorted(((len(v),v) for v in groups.values()),reverse=True)

def resize_float(src,out_hw,filt):
    im=Image.fromarray(np.asarray(src,dtype=np.float32),mode="F")
    return np.array(im.resize((out_hw[1],out_hw[0]),resample=filt),dtype=float)

def operator(h,w,filt):
    cols=[]
    for i in range(h*w):
        basis=np.zeros((h,w),dtype=np.float32); basis.ravel()[i]=1.0
        cols.append(resize_float(basis,(7,7),filt).ravel())
    return np.stack(cols,axis=1)

def model_catalog():
    out=[]
    for name,filt in FILTERS.items():
        for h in range(1,7):
            for w in range(1,7):
                a=operator(h,w,filt); out.append((name,filt,h,w,a,np.linalg.pinv(a)))
    return out

def fit_target(target,catalog):
    y=np.asarray(target,dtype=float).ravel(); reports=[]
    for name,filt,h,w,a,pinv in catalog:
        source=pinv@y; continuous=a@source
        rmse=float(np.sqrt(np.mean((continuous-y)**2))); max_abs=float(np.max(np.abs(continuous-y)))
        clipped=np.clip(np.rint(source),0,255).astype(np.uint8).reshape(h,w)
        rendered=np.array(Image.fromarray(clipped,"L").resize((7,7),resample=filt),dtype=np.uint8)
        byte_errors=int(np.count_nonzero(rendered!=target))
        reports.append({"filter":name,"source_h":h,"source_w":w,"source_dof":h*w,
                        "continuous_rmse":rmse,"continuous_max_abs":max_abs,
                        "uint8_byte_errors":byte_errors,"source_values":clipped.tolist()})
    return min(reports,key=lambda r:(r["continuous_rmse"],r["source_dof"],r["filter"],r["source_h"],r["source_w"])),reports

def calibrate(target,trials=NULL_TRIALS):
    catalog=model_catalog(); best,reports=fit_target(target,catalog)
    exact=[r for r in reports if r["uint8_byte_errors"]==0]
    exact_continuous=[r for r in reports if r["continuous_max_abs"]<1e-9]
    best_by_dof={}
    for cap in (1,4,9,16,25,36):
        r=min((x for x in reports if x["source_dof"]<=cap),key=lambda x:x["continuous_rmse"])
        best_by_dof[str(cap)]={k:r[k] for k in ("filter","source_h","source_w","source_dof",
                                                 "continuous_rmse","uint8_byte_errors")}
    rng=np.random.default_rng(NULL_SEED); n250=int(np.sum(target==250)); vals=[]
    for _ in range(trials):
        flat=np.full(49,255,dtype=np.uint8); flat[rng.choice(49,n250,replace=False)]=250
        b,_=fit_target(flat.reshape(7,7),catalog); vals.append(b["continuous_rmse"])
    a=np.array(vals)
    return {"target_rows":[" ".join(map(str,row)) for row in target],"target_250_count":n250,
            "catalog_models":len(catalog),"best_continuous":best,
            "exact_uint8_models":exact,"exact_uint8_model_count":len(exact),
            "exact_continuous_model_count":len(exact_continuous),"best_by_max_source_dof":best_by_dof,
            "null_trials":trials,"null_seed":NULL_SEED,
            "null_rmse":{"real":best["continuous_rmse"],"mean":float(a.mean()),
                         "min":float(a.min()),"max":float(a.max()),
                         "p_le_real":float((1+np.sum(a<=best["continuous_rmse"]))/(trials+1))}}

def self_test():
    assert sha256_of(IMAGE_PATH)==EXPECTED_SHA256
    target,mods,groups=canonical_patch(); assert target.shape==(7,7)
    assert set(np.unique(target))=={250,255}; assert len(mods)>=4
    assert mods==EXPECTED_CANONICAL_MODULES
    catalog=model_catalog(); assert len(catalog)==216
    planted=np.array([[250,255],[255,250]],dtype=np.uint8)
    rendered=np.array(Image.fromarray(planted,"L").resize((7,7),Image.Resampling.NEAREST))
    best,reports=fit_target(rendered,catalog)
    assert any(r["filter"]=="nearest" and r["source_h"]==2 and r["source_w"]==2 and
               r["uint8_byte_errors"]==0 for r in reports)
    real_best,real_reports=fit_target(target,catalog)
    got=(real_best["filter"],real_best["source_h"],real_best["source_w"],
         real_best["continuous_rmse"],real_best["uint8_byte_errors"])
    assert got==EXPECTED_BEST,got
    assert not any(r["uint8_byte_errors"]==0 or r["continuous_max_abs"]<1e-9 for r in real_reports)
    print(f"[*] self-test OK: source pinned; canonical 7x7 patch occurs in {len(mods)} modules; "
          "216 smaller-source/filter models built; planted 2x2 nearest-neighbor source recovered exactly.")

def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument("--self-test",action="store_true")
    p.add_argument("--trials",type=int,default=NULL_TRIALS);p.add_argument("--json",action="store_true")
    a=p.parse_args();self_test()
    if a.self_test:return
    target,mods,groups=canonical_patch();report=calibrate(target,a.trials)
    report["canonical_modules"]=mods;report["module_patch_group_sizes"]=[g[0] for g in groups]
    if a.json:print(json.dumps(report,indent=2));return
    print("[*] canonical modules:",mods);print("[*] best:",report["best_continuous"])
    print("[*] exact uint8 models:",report["exact_uint8_model_count"]);print("[*] null:",report["null_rmse"])

if __name__=="__main__":main()
