#!/usr/bin/env python3
"""Raw authenticated-asset-byte password audit (P32 Family 3).

Executes doc/GSMG_BRAINSTORM_BACKLOG_LEDGER.md's "P32 Family 3 -- raw
binary asset bytes as password material" (source:
doc/Brainstorms/2026-08-14 - P32 New Attack Surfaces Beyond Text
Recombination.md, "Candidate family 3"). No phase before this one has
hashed the *raw on-disk bytes* of a puzzle asset -- as opposed to its
pixel/visible content, already extensively covered elsewhere -- as
password preimage material.

**Correction history (three rounds, all same-day, before this script was
ever committed):**

**Round 1** -- the first version built its manifest from
git-commit-message inference alone (e.g. "the site's favicon/logo
assets" grouping several files together) and got the provenance wrong
for most of it:

1. `phase2.png`, `phase3.png`, `theseedisplanted.png`, and
   `SalPhaseIonCosmicDuality.png` were claimed as "authenticated
   historical response bytes." FINDINGS.md Phase 162 already
   established -- before this script was ever written -- that these four
   are *browser screenshots* (URL bar visible in-frame), not server
   response bytes: "The PNG bytes were generated by someone's screenshot
   tool, not by the creator or the gsmg.io server." They belong in the
   source document's explicitly non-core "community copy" class and are
   excluded here.
2. `favicon.png`, both favicon SVGs, and the 8 `gsmg_icon_*.png` crops
   were claimed authenticated by association with `favicon_small.png`
   (which *is* independently Wayback-confirmed). Cross-referencing the
   local site mirror's own manifest
   (`/home/loginwashere/projects/gsmg-site-mirror/_manifest.json`, not
   part of this git repo) shows this was false: those files' *own*
   fetch timestamps are `20260405`/`20260418` -- live fetches of the
   currently-restored gsmg.io in April 2026, whose operator is
   explicitly unresolved (FINDINGS.md Phase 329) -- not puzzle-era
   captures.

Round 1 concluded (wrongly) that only `favicon_small.png` and
`logo_medium.png` in that mirror carried old timestamps.

**Round 2** -- caught that round 1's own image-only filter of that same
mirror manifest had in fact turned up `background-full.jpg`
(`20220706222904`), `front_bg_1920.svg` (`20230626163906`), and
`front_bittrex.svg` (`20230718041248`) as pre-cutoff images -- they were
mis-summarized as "everything else... excluded," not actually re-checked
against the stated cutoff. A mime-type filter also silently dropped
`lato-regular-webfont.woff` (`20220706220803`, `application/font-woff`),
the one font Family 3's own scope explicitly covers. All four are added,
copied into this repo (`doc/img/site_mirror/`, mirroring the source
mirror's own relative paths) rather than read live from the external,
uncommitted mirror directory. Separately, round 1 asserted only aggregate
counts (88/83/81/76) for the Telegram creator-media class, which a
differently-composed corpus of the same sizes would pass silently -- so
round 2 added `CANONICAL_PAYLOAD_SET_DIGEST`, a SHA-256 of the 76
resolved unique payload hashes themselves (sorted, newline-joined,
re-hashed), but only asserted it in `self_test()`.

**Round 3** -- caught two more issues in round 2's own fix. First,
`CANONICAL_PAYLOAD_SET_DIGEST` was checked only inside `self_test()`; the
normal `--run` path called `full_manifest()` directly, so a
same-size-different-bytes corpus could still have produced an
authoritative-looking report without the pin actually blocking it. Fixed
by moving the check into `core_creator_media()` itself, which both
`self_test()` and `run()` go through -- verified with a planted mismatch
that it now raises `ValueError`. Second, a broader re-check of the mirror
manifest (all mime types, not just images) found 59 total pre-cutoff,
non-`/shared/` entries: 6 eligible (image/font, all 6 in the manifest)
and 53 excluded -- round 2's own write-up had said "the other 55" without
re-deriving the number. The 53 excluded are `text/html`
(`register?referral=...` pages), `application/javascript`
(`app.js`/`vendor.js` bundles, mostly near-duplicate builds across
dates), `text/css`, and `.js.map` files -- explicitly out of Family 3's
own declared scope ("image asset", "the favicon", "non-image binary
asset (fonts, if any were mirrored)"), not silently included.

Round 3 also fixed an overstatement: describing all 7 site assets as
"independently confirmed pre-2023" implied every one had a second,
separately-recorded source the way `favicon_small.png` does (a live
Wayback CDX capture, doc/GSMG_FAVICON_WAYBACK_CHRONOLOGY_AUDIT.md,
recorded before this mirror was ever consulted). The other 6 rest on the
local mirror tool's own `_manifest.json` alone -- a single external,
uncommitted source, not independently re-verified. `doc/img/site_mirror/
PROVENANCE.json`, committed alongside the 4 new asset files, pins that
source manifest's own SHA-256 and the exact 6 accepted rows (orig URL,
timestamp, mime, local path, byte count) verbatim, cross-checked in
`self_test()` against the actual committed files -- this makes the claim
a reproducible, checkable artifact, not a stronger form of evidence than
it was.

The corrected core universe has two classes, matching the source
document's own two non-excluded provenance classes exactly:

**A. Authenticated historical site-response bytes (7 files):**

  - `doc/img/icons/favicon_small.png` -- SHA-256 independently confirmed
    against a live Wayback CDX capture, 2019-04-28
    (doc/GSMG_FAVICON_WAYBACK_CHRONOLOGY_AUDIT.md).
  - `doc/img/icons/logo_medium.png` -- confirmed present in the site
    mirror with an old (2020-08-30) fetch timestamp, and per Phase 162
    shares an identical Adobe XMP export batch timestamp with
    `favicon_small.png` ("confirming they're from the same branding
    export batch").
  - `doc/img/gsmg_puzzle_stage1.png` (== `puzzle.png`) -- present
    unchanged in this repo since 2020-04-25 (commit `c4b6a20`) and
    byte-identical to a 2025-05-20 Wayback capture of
    `beta.gsmg.io/puzzle` (FINDINGS.md, on-chain/DNS forensics phase).
    That is retrospective cross-observation stability (a 2020 repo copy
    matching a 2025 capture), not an independently-dated *original*
    server response the way `favicon_small.png`'s 2019 CDX capture is --
    stated precisely rather than implied stronger than it is. 5+ years
    of byte-identical observation while the rest of the site became an
    unrelated product is still the basis for treating it as reliable.
  - `doc/img/site_mirror/img/background-full.jpg` -- mirror fetch
    timestamp `20220706222904`.
  - `doc/img/site_mirror/img/front_bg_1920.svg` -- mirror fetch
    timestamp `20230626163906`.
  - `doc/img/site_mirror/img/front_bittrex.svg` -- mirror fetch
    timestamp `20230718041248`.
  - `doc/img/site_mirror/fonts/lato-regular-webfont.woff` -- mirror fetch
    timestamp `20220706220803`; the only font in the local mirror with
    pre-cutoff provenance (`lato-regular-webfont.woff2` also exists but
    only with a `20260418` live-fetch timestamp, excluded).

**B. Telegram-export creator-authored originals (76 unique payloads):**

  Phase 248 (`architect_mirror_selector_audit.py`) already froze the
  *complete* creator-media universe across both known exports: 88
  records (`EXPECTED_CREATOR_MEDIA_IDS`, imported from that module, not
  duplicated here), 83 unique payload hashes. Restricting to messages
  dated before P32TRAILING's own established chronology-graph bound
  (`blob_chronology_dependency_graph.py`'s `first_publicly_seen:
  {"not_after": "2023-08"}`) -- rather than inventing a narrower
  relevance filter -- gives 81 records, independently re-derived here
  (not merely re-quoted) and re-verified against both raw exports with
  zero missing message IDs: 76 unique payload hashes. This is a
  materially larger, and more honestly sourced, core universe than the
  one creator attachment (`gsmg_stage0_original_telegram.jpg`) that
  happened to already be committed to this repo -- keeping only that one
  was a repository-location selection artifact, not a provenance
  argument.

  Review round 2 also caught that self_test() only asserted aggregate
  counts (88/83/81/76) for this class, which a differently-composed
  corpus of the same sizes would pass silently. `core_creator_media()`'s
  actual resolved payload-hash set is now pinned by
  `CANONICAL_PAYLOAD_SET_DIGEST`: the 76 unique SHA-256 hex digests,
  sorted ascending, newline-joined, SHA-256'd again -- a serialization
  chosen to depend only on the tested *bytes*, not on which particular
  (export, message id) happens to carry each payload (two different
  messages can share one payload hash, e.g. a reposted image; the digest
  should not depend on an arbitrary tie-break of which one "represents"
  it).

**Excluded, with reasons (not silently dropped):**

  - `phase2.png`, `phase3.png`, `theseedisplanted.png`,
    `SalPhaseIonCosmicDuality.png` -- confirmed browser screenshots, not
    server bytes (Phase 162, see above).
  - `favicon.png`, `favicon_small.svg`, `favicon_small_night.svg`, the 8
    `gsmg_icon_*.png` crops, `lato-regular-webfont.woff2`, and every
    other non-`/shared/` mirror entry with a `2025`/`2026` fetch
    timestamp (`popup_img_error.png`, menu icons, `front_binance.svg`,
    etc.) -- confirmed live fetches of the operator-unresolved restored
    site; several are plausibly the *current unrelated subscription-bot
    product's* UI, not puzzle content at all.
  - The 53 non-image/font, non-`/shared/` mirror entries with pre-cutoff
    timestamps (`register?referral=...` pages, `app.js`/`vendor.js`
    bundles, `app.css`, `.js.map` files) -- real historical HTTP
    responses, but outside Family 3's own declared scope (images and
    fonts only); including page/script/style text as raw password-byte
    material would be a materially different, un-preregistered
    experiment, not a Family 3 coverage gap.
  - All 55 `/shared/` entries in the site mirror -- dynamically
    generated per-URL social-preview artifacts (paired `.html`/`.png`),
    unclear generation mechanism and authorship, same live-fetch
    contamination risk, none carries a pre-2020 timestamp.
  - `favicon.ico` -- 0 bytes, empty.
  - `photo_2020-04-26_09-24-30.jpg` -- carries `G-X2SH-001`'s own
    already-documented chronology conflict.
  - Any of the 88 creator-media records dated on/after 2023-09 (7
    records excluded on this basis alone).
  - Every non-creator ("community") Telegram media file --
    `doc/telegram_shortlist_fullsize/*` (33 images, senders never the
    creator account) and `doc/telegram_vovam_deleted_thread/*_annotated*`
    (3 locally-annotated derivatives) -- the source document's
    explicitly non-core classes.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from cb_common import (  # noqa: E402
    BLOBS,
    ECB_CIPHER_VARIANTS,
    EXTENDED_CIPHER_VARIANTS,
    KDF_VARIANTS,
    KEY_WRAP_KDF_VARIANTS,
    STREAM_CIPHER_VARIANTS,
    aes_key_wrap,
    aes_keywrap_try_open_bytes,
    aes_try_open_bytes,
    aes_try_open_ecb_bytes,
    aes_try_open_stream_bytes,
    derive_kek,
)
from architect_mirror_selector_audit import (  # noqa: E402
    EXPECTED_CREATOR_MEDIA_IDS,
    SOLVER_EXPORT_DIR,
    SUPPORT_EXPORT_DIR,
    load_export,
    media_path,
)

REPO_ROOT = Path(__file__).resolve().parents[2]

# Class A -- (relative path, expected SHA-256, provenance note). Pinned so
# a future edit is caught by self_test() rather than silently changing
# what this audit covers.
SITE_ASSETS = [
    ("doc/img/icons/favicon_small.png",
     "934f46d6a0a168a7ca2af725604d7e1dab8ee825ad0d7c682dbb252cc2be1423",
     "site favicon; SHA-256 confirmed by live Wayback CDX capture 2019-04-28"),
    ("doc/img/icons/logo_medium.png",
     "eb360eeff3501b94e40d8ffc4364e795016fd39acc47a64870b727c119ec3a47",
     "site logo raster; old (2020-08-30) mirror fetch timestamp, shares an "
     "XMP export batch with favicon_small.png (Phase 162)"),
    ("doc/img/gsmg_puzzle_stage1.png",
     "38125bbdf1ea58b9b30b075bc6bf71e4089d04bba37098317e47097e2f2a1830",
     "gsmg.io/puzzle QR page; 2020-04-25 repo copy byte-identical to a "
     "2025-05-20 Wayback capture of beta.gsmg.io/puzzle (retrospective "
     "cross-observation stability, not an independently-dated original "
     "capture the way favicon_small.png's is)"),
    ("doc/img/site_mirror/img/background-full.jpg",
     "249e3012eb381474af5e092ce2a01d8b9ab931e9332ad034172ec931dd85ac08",
     "site background image; mirror fetch timestamp 20220706222904"),
    ("doc/img/site_mirror/img/front_bg_1920.svg",
     "dc8fa8a4932dde6a6df57319ad1b7f62fcec1b4bef94503563a1a510170f1937",
     "site background SVG; mirror fetch timestamp 20230626163906"),
    ("doc/img/site_mirror/img/front_bittrex.svg",
     "3319d9e8a8154237a9b40b35c9961fddcedc83b5ad5f61305a02d9b4bc938d5e",
     "site exchange-badge SVG; mirror fetch timestamp 20230718041248"),
    ("doc/img/site_mirror/fonts/lato-regular-webfont.woff",
     "9ea835c0b3da06e21880c6426ac7894919209e60b7743a24862a6f0f39c24954",
     "site webfont; mirror fetch timestamp 20220706220803 (the .woff2 "
     "sibling is excluded -- only a 20260418 live-fetch timestamp)"),
]

# Class B -- Phase 248's frozen creator-media universe (88 records, 83
# unique payloads), restricted here to P32TRAILING's own established
# chronology-graph bound. Strictly-less-than this ISO-date-prefix string
# means "dated no later than 2023-08".
CREATOR_MEDIA_DATE_CUTOFF = "2023-09"

EXPECTED_TOTAL_RECORDS = 88
EXPECTED_UNIQUE_ALL_DATES = 83  # Phase 248's own figure, re-verified here
EXPECTED_PRECUTOFF_RECORDS = 81
EXPECTED_PRECUTOFF_UNIQUE = 76

# Content-only tamper-evidence pin for the 76 pre-cutoff unique payloads:
# their SHA-256 hex digests, sorted ascending, newline-joined, hashed
# again. Depends only on the tested bytes -- not on which (export,
# message id) label happens to carry each payload, so a repost of the
# same image under a different message id does not change this value.
CANONICAL_PAYLOAD_SET_DIGEST = (
    "ad3d6225408eb952524d7a76d7626add195a9f709d7776a720887b6e68c0b5c4"
)

EXPECTED_SITE_ASSET_COUNT = len(SITE_ASSETS)
EXPECTED_FORMS_PER_CANDIDATE = 3  # literal bytes, raw SHA-256 digest, hex SHA-256 text

# Full-oracle convention (matches Phase 379's corrected CBC set).
CBC_KDF_VARIANTS = KDF_VARIANTS + EXTENDED_CIPHER_VARIANTS
KEYWRAP_FORMS_PER_CONFIG = 4  # RFC 3394/5649 x default/OpenSSL-custom-IV

ORACLE_FAMILIES = (
    ("cbc", aes_try_open_bytes, CBC_KDF_VARIANTS, 1),
    ("ecb", aes_try_open_ecb_bytes, ECB_CIPHER_VARIANTS, 1),
    ("stream", aes_try_open_stream_bytes, STREAM_CIPHER_VARIANTS, 1),
    ("keywrap", aes_keywrap_try_open_bytes, KEY_WRAP_KDF_VARIANTS, KEYWRAP_FORMS_PER_CONFIG),
)

# "initially target P32TRAILING only" per the source brainstorm document.
TARGET_BLOBS = {"P32TRAILING": BLOBS["P32TRAILING"]}


def resolve_creator_media():
    """Every (group, id) in Phase 248's frozen list, resolved against the
    two real export directories: (label, full_path, sha256, date) rows.
    Raises if an export directory or a referenced media file is missing --
    this audit's real run needs the actual bytes, same as every other
    Telegram-media-dependent script in this project."""
    export_dirs = {"solver": SOLVER_EXPORT_DIR, "support": SUPPORT_EXPORT_DIR}
    exports = {label: load_export(d) for label, d in export_dirs.items()}
    by_id = {
        label: {m["id"]: m for m in data["messages"] if isinstance(m, dict)}
        for label, data in exports.items()
    }

    rows = []
    for group, ids in EXPECTED_CREATOR_MEDIA_IDS.items():
        for mid in ids:
            message = by_id[group][mid]
            rel_media = media_path(message)
            full_path = export_dirs[group] / rel_media
            sha256 = hashlib.sha256(full_path.read_bytes()).hexdigest()
            rows.append((f"{group}/{mid}", full_path, sha256, message.get("date", "")))
    return rows


def core_creator_media():
    """Deduplicated (label, full_path, sha256) rows for the 76 unique
    payloads dated before CREATOR_MEDIA_DATE_CUTOFF. Keeps the
    earliest-dated record when the same payload hash appears more than
    once. Validates CANONICAL_PAYLOAD_SET_DIGEST here -- not only in
    self_test() -- so the normal --run path (full_manifest() -> run())
    cannot silently score a differently-composed corpus of the same size
    as though it were this pinned one."""
    rows = resolve_creator_media()
    precutoff = [r for r in rows if r[3] < CREATOR_MEDIA_DATE_CUTOFF]
    precutoff.sort(key=lambda r: r[3])
    seen = {}
    for label, full_path, sha256, date in precutoff:
        seen.setdefault(sha256, (label, full_path, sha256))
    resolved = list(seen.values())

    actual_digest = payload_set_digest(resolved)
    if actual_digest != CANONICAL_PAYLOAD_SET_DIGEST:
        raise ValueError(
            f"creator-media payload set digest mismatch "
            f"(expected {CANONICAL_PAYLOAD_SET_DIGEST}, got {actual_digest}) -- "
            "resolved Telegram media bytes no longer match this manifest's pin"
        )
    return resolved


def payload_set_digest(rows):
    """CANONICAL_PAYLOAD_SET_DIGEST's own computation, applied to any
    (label, path, sha256) row list -- content-only, order-independent."""
    ordered = sorted({sha256 for _, _, sha256 in rows})
    return hashlib.sha256("\n".join(ordered).encode()).hexdigest()


def load_site_manifest():
    """Resolve SITE_ASSETS against disk, asserting each pinned SHA-256."""
    resolved = []
    for rel_path, expected_sha256, note in SITE_ASSETS:
        full_path = REPO_ROOT / rel_path
        raw = full_path.read_bytes()
        actual_sha256 = hashlib.sha256(raw).hexdigest()
        if actual_sha256 != expected_sha256:
            raise ValueError(
                f"{rel_path}: pinned SHA-256 mismatch "
                f"(expected {expected_sha256}, got {actual_sha256}) -- "
                "file changed since this manifest was frozen"
            )
        resolved.append((rel_path, full_path, expected_sha256))
    return resolved


def full_manifest():
    """Class A (7 site assets) + Class B (76 unique pre-cutoff creator
    media): (label, Path, sha256) rows, asserted disjoint by content hash."""
    site = load_site_manifest()
    creator = core_creator_media()
    site_hashes = {sha for _, _, sha in site}
    creator_hashes = {sha for _, _, sha in creator}
    overlap = site_hashes & creator_hashes
    if overlap:
        raise ValueError(f"site/creator-media manifests overlap by content: {overlap}")
    return site + creator


def asset_forms(path: Path):
    """(form_kind, bytes) triples for one asset: literal, raw digest, hex digest."""
    raw = path.read_bytes()
    digest = hashlib.sha256(raw).digest()
    return [
        ("literal_file_bytes", raw),
        ("sha256_raw_bytes", digest),
        ("sha256_hex", digest.hex().encode()),
    ]


def run(blobs=None):
    active_blobs = TARGET_BLOBS if blobs is None else blobs
    manifest = full_manifest()

    materials_tested = 0
    effective_attempts = 0
    hits = []
    for label, full_path, _sha256 in manifest:
        for form_kind, material in asset_forms(full_path):
            materials_tested += 1
            for family_name, oracle_fn, variants, forms_per_config in ORACLE_FAMILIES:
                effective_attempts += len(variants) * len(active_blobs) * forms_per_config
                if family_name == "keywrap":
                    for tag, wrap_kind, kdf_label, key_len, unwrapped in oracle_fn(
                        material, kdf_variants=variants, blobs=active_blobs,
                    ):
                        hits.append({
                            "asset": label, "form": form_kind, "family": family_name,
                            "blob": tag, "kdf": f"{kdf_label}/aes{key_len * 8}/{wrap_kind}",
                            "plaintext_hex": unwrapped.hex(),
                        })
                else:
                    result = oracle_fn(material, kdf_variants=variants, blobs=active_blobs)
                    if result:
                        tag, body, kdf_label, key_len = result
                        hits.append({
                            "asset": label, "form": form_kind, "family": family_name,
                            "blob": tag, "kdf": f"{kdf_label}/aes{key_len * 8}",
                            "plaintext_hex": body.hex(),
                        })

    return {
        "candidate_count": len(manifest),
        "materials_tested": materials_tested,
        "blobs": tuple(active_blobs),
        "oracle_families": [name for name, _, _, _ in ORACLE_FAMILIES],
        "total_variant_configs": sum(len(v) for _, _, v, _ in ORACLE_FAMILIES),
        "effective_decrypt_attempts": effective_attempts,
        "hits": hits,
        "total_hits": len(hits),
    }


def self_test():
    # Class A
    site = load_site_manifest()
    assert len(site) == EXPECTED_SITE_ASSET_COUNT
    assert len({sha for _, _, sha in site}) == EXPECTED_SITE_ASSET_COUNT, "duplicate site asset"

    # Class B -- re-derive Phase 248's own figures independently, not just
    # assert them, so a future export change is caught.
    all_rows = resolve_creator_media()
    assert len(all_rows) == EXPECTED_TOTAL_RECORDS, len(all_rows)
    assert len({r[2] for r in all_rows}) == EXPECTED_UNIQUE_ALL_DATES, (
        len({r[2] for r in all_rows}), "Phase 248 recorded 83 unique payloads"
    )
    precutoff = [r for r in all_rows if r[3] < CREATOR_MEDIA_DATE_CUTOFF]
    assert len(precutoff) == EXPECTED_PRECUTOFF_RECORDS, len(precutoff)
    creator = core_creator_media()
    assert len(creator) == EXPECTED_PRECUTOFF_UNIQUE, len(creator)
    # Content-only pin: catches a same-size corpus with different bytes,
    # which the count assertions above cannot.
    actual_digest = payload_set_digest(creator)
    assert actual_digest == CANONICAL_PAYLOAD_SET_DIGEST, (
        actual_digest, CANONICAL_PAYLOAD_SET_DIGEST,
    )

    manifest = full_manifest()
    assert len(manifest) == EXPECTED_SITE_ASSET_COUNT + EXPECTED_PRECUTOFF_UNIQUE

    forms0 = asset_forms(manifest[0][1])
    assert len(forms0) == EXPECTED_FORMS_PER_CANDIDATE
    assert forms0[1][1] == hashlib.sha256(forms0[0][1]).digest()
    assert forms0[2][1] == hashlib.sha256(forms0[0][1]).digest().hex().encode()

    total_materials = sum(len(asset_forms(fp)) for _, fp, _ in manifest)
    assert total_materials == len(manifest) * EXPECTED_FORMS_PER_CANDIDATE

    assert len(CBC_KDF_VARIANTS) == 24, len(CBC_KDF_VARIANTS)
    total_configs = sum(len(v) for _, _, v, _ in ORACLE_FAMILIES)
    assert total_configs == 84, total_configs  # 24 CBC + 12 ECB + 36 stream + 12 keywrap
    assert tuple(TARGET_BLOBS) == ("P32TRAILING",)

    expected_effective = total_materials * (24 + 12 + 36 + 12 * KEYWRAP_FORMS_PER_CONFIG)
    report = run(blobs=TARGET_BLOBS)
    assert report["effective_decrypt_attempts"] == expected_effective, (
        report["effective_decrypt_attempts"], expected_effective,
    )

    _self_test_keywrap_hit_handling()
    _self_test_favicon_small_matches_wayback_hash()
    _self_test_provenance_json_matches_site_assets()

    print(
        f"[*] self-test OK: {EXPECTED_SITE_ASSET_COUNT} site assets + "
        f"{EXPECTED_PRECUTOFF_UNIQUE} unique pre-cutoff creator-media payloads "
        f"(re-derived from {EXPECTED_TOTAL_RECORDS} frozen records, "
        f"{EXPECTED_UNIQUE_ALL_DATES} unique all-dates matching Phase 248, "
        f"{EXPECTED_PRECUTOFF_RECORDS} records dated < {CREATOR_MEDIA_DATE_CUTOFF}) "
        f"= {len(manifest)} candidates x {EXPECTED_FORMS_PER_CANDIDATE} forms = "
        f"{total_materials} materials, {total_configs} full-oracle configs, "
        f"P32TRAILING-only scope, {expected_effective} effective decrypt attempts, "
        f"Key Wrap hit handling verified"
    )


def _self_test_keywrap_hit_handling():
    """A planted Key Wrap positive is correctly recorded, not just an
    empty-list no-crash (mirrors the same check added by Phase 379)."""
    manifest = full_manifest()
    _, full_path, _ = manifest[0]
    material = full_path.read_bytes()
    salt = b"01234567"
    variant = KEY_WRAP_KDF_VARIANTS[0]
    kdf_kind, kdf_param, key_len = variant
    kek = derive_kek(kdf_kind, kdf_param, salt, material, key_len)
    key_material = b"0123456789ABCDEF"
    wrapped = aes_key_wrap(kek, key_material)

    hits = []
    for tag, wrap_kind, kdf_label, unwrapped_key_len, unwrapped in aes_keywrap_try_open_bytes(
        material, kdf_variants=[variant], blobs={"SYNTH": (salt, wrapped)},
    ):
        hits.append((tag, wrap_kind, kdf_label, unwrapped_key_len, unwrapped))
    assert any(
        tag == "SYNTH" and unwrapped == key_material and "rfc3394-default" in wrap_kind
        for tag, wrap_kind, kdf_label, unwrapped_key_len, unwrapped in hits
    ), f"planted Key Wrap hit not found in {hits!r}"


def _self_test_favicon_small_matches_wayback_hash():
    """Cross-checks this module's own pinned hash against the independently
    recorded Wayback CDX authentication in
    doc/GSMG_FAVICON_WAYBACK_CHRONOLOGY_AUDIT.md, rather than trusting this
    module's docstring claim alone."""
    expected = "934f46d6a0a168a7ca2af725604d7e1dab8ee825ad0d7c682dbb252cc2be1423"
    entry = next(a for a in SITE_ASSETS if a[0] == "doc/img/icons/favicon_small.png")
    assert entry[1] == expected


def _self_test_provenance_json_matches_site_assets():
    """doc/img/site_mirror/PROVENANCE.json's 6 accepted rows are checked
    against the actual committed files -- byte count and, via each row's
    `local` basename, the matching SITE_ASSETS entry's own pinned SHA-256
    -- so the committed provenance record cannot drift from what
    self_test() actually verifies elsewhere. Self-contained: no dependency
    on the external, uncommitted source mirror directory."""
    provenance_path = REPO_ROOT / "doc" / "img" / "site_mirror" / "PROVENANCE.json"
    provenance = json.loads(provenance_path.read_text())
    rows = provenance["accepted_rows"]
    assert len(rows) == 6, len(rows)

    expected_basenames = {
        "favicon_small.png", "logo_medium.png", "background-full.jpg",
        "front_bg_1920.svg", "front_bittrex.svg", "lato-regular-webfont.woff",
    }
    actual_basenames = {Path(row["local"]).name for row in rows}
    assert actual_basenames == expected_basenames, (
        actual_basenames, expected_basenames,
    )  # exact set, not just a count -- rejects a duplicated/substituted row

    site_by_basename = {Path(rel).name: (rel, sha) for rel, sha, _note in SITE_ASSETS}
    for row in rows:
        basename = Path(row["local"]).name
        assert basename in site_by_basename, f"{basename} not in SITE_ASSETS"
        rel_path, expected_sha256 = site_by_basename[basename]
        full_path = REPO_ROOT / rel_path
        raw = full_path.read_bytes()
        assert len(raw) == row["bytes"], (basename, len(raw), row["bytes"])
        assert hashlib.sha256(raw).hexdigest() == expected_sha256, basename


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--self-test", action="store_true")
    parser.add_argument("--run", action="store_true")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()
    if args.self_test:
        self_test()
        return
    if args.run:
        report = run()
    else:
        report = {"note": "pass --run or --self-test"}
    if args.json:
        print(json.dumps(report, indent=2, default=repr))
    else:
        for key, value in report.items():
            print(f"{key}: {value}")


if __name__ == "__main__":
    main()
